server:
  port: 80

eureka:
  client:
    #false表示不向之策中心注册自己
    register-with-eureka: false
    #flase表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    #fetchRegistry: true
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://Eureka7001.com:7001/eureka

feign:
  hystrix:
    enable: true