server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    #fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://Eureka7001.com:7001/eureka,http://Eureka7002.com:7002/eureka
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    #feign以什么级别监控哪个接口
    org.example.service.IPaymentFeignService: debug


